apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: kfl9ccvgp-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kfl9ccvgp-nodejs 
  name: kfl9ccvgp-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: kfl9ccvgp-nodejs 
